### Notes
- The json defines all the connections so if "is_reciprocal": true, it means there is a recirocal connection

In [1]:
import json
import yaml
import os
import pandas as pd

In [2]:

slices_dir = os.path.join('/home/ellismith/OlfactoryBulb/olfactorybulb/slices')

#file_names = ['GCs__MCs', 'GCs__TCs']
file_names = ['GCs__TCs']

for file_name in file_names:

    # import file into a dictionary
    with open(f'{slices_dir}/DorsalColumnSlice/{file_name}.json','r') as f:
        cells = json.load(f)

    # create dictionary to initalize DataFrame with
    df_contents = {'Cell': ['MC1', 'MC2', 'MC3', 'MC4', 'MC5', 
                            'TC1', 'TC2', 'TC3', 'TC4', 'TC5', 
                            'GC1', 'GC2', 'GC3', 'GC4', 'GC5'],
                    'Source': [0, 0, 0, 0, 0,
                                0, 0, 0, 0, 0,
                                0, 0, 0, 0, 0],
                    'Destination': [0, 0, 0, 0, 0,
                                    0, 0, 0, 0, 0,
                                    0, 0, 0, 0, 0]}

    # initialize DataFrame
    syn_df = pd.DataFrame(df_contents)

    # set the index of DataFrame to Cell 
    syn_df = syn_df.set_index('Cell')

    # iterate over connections (entries) in file
    for entry in cells['entries']:
        # get the source and destination cell types (first three characters, i.e. MC5, MC4, ...) 
        source_cell = entry['source_section'][:3]
        dest_cell = entry['dest_section'][:3]

        # get row of DataFrame that matches the source and destination cell types
        source_row = syn_df.loc[source_cell]  # syn_df[syn_df['Cell'] == source_cell]
        dest_row = syn_df.loc[dest_cell]  # syn_df[syn_df['Cell'] == dest_cell]

        # check that all synapses are reciprocal
        assert entry['is_reciprocal'] == True 
        
        # increment source and destination cell type counts
        syn_df.at[source_cell,'Source'] = source_row.Source + 1
        syn_df.at[dest_cell,'Destination'] = dest_row.Source + 1

    # write DataFrame to pickle (for reimporting as a DataFrame) and yaml (for viewing) files
    syn_df.to_pickle(f'{slices_dir}/{file_name}_synapse_counts.pkl', protocol=3)
    with open(f'{slices_dir}/{file_name}_synapse_counts.yaml', 'w') as outfile:
        yaml.dump(syn_df.to_dict(),outfile)

In [3]:
syn_df

      Source  Destination
Cell
MC1        0            0
MC2        0            0
MC3        0            0
MC4        0            0
MC5        0            0
TC1        0            0
TC2        0            0
TC3        0            1
TC4        0            1
TC5        0            1
GC1      571            0
GC2        0            0
GC3      709            0
GC4      337            0
GC5      134            0

In [37]:

slices_dir = os.path.join('/home/ellismith/OlfactoryBulb/olfactorybulb/slices')

file_names = ['GCs__MCs']

for file_name in file_names:

    # import file into a dictionary
    with open(f'{slices_dir}/DorsalColumnSlice/{file_name}.json','r') as f:
        cells = json.load(f)

    # create dictionary to initalize DataFrame with
    df_contents = {
        'Exc_Cell': ['MC1', 'MC2', 'MC3', 'MC4', 'MC5', 
                            'TC1', 'TC2', 'TC3', 'TC4', 'TC5'],
                    'GC1': [0, 0, 0, 0, 0,
                                0, 0, 0, 0, 0],
                    'GC2': [0, 0, 0, 0, 0,
                                    0, 0, 0, 0, 0],
                    'GC3': [0, 0, 0, 0, 0,
                                0, 0, 0, 0, 0],
                    'GC4': [0, 0, 0, 0, 0,
                                0, 0, 0, 0, 0],
                    'GC5': [0, 0, 0, 0, 0,
                                0, 0, 0, 0, 0]}

    # initialize DataFrame
    syn_df = pd.DataFrame(df_contents)

    # set the index of DataFrame to Cell 
    syn_df = syn_df.set_index('Exc_Cell')

    # iterate over connections (entries) in file
    for entry in cells['entries']:
        # get the source and destination cell types (first three characters, i.e. MC5, MC4, ...) 
        source_cell = entry['source_section'][:3]
        dest_cell = entry['dest_section'][:3]

        # check that all synapses are reciprocal
        assert entry['is_reciprocal'] == True 
        
        # increment synapse counts - all GCs are sources and all MCs and TCs are dest's
        syn_df.loc[dest_cell][source_cell] = syn_df.loc[dest_cell][source_cell] + 1


    # write DataFrame to pickle (for reimporting as a DataFrame) and yaml (for viewing) files
    syn_df.to_pickle(f'{slices_dir}/{file_name}_synapse_counts.pkl', protocol=3)
    with open(f'{slices_dir}/{file_name}_synapse_counts.yaml', 'w') as outfile:
        yaml.dump(syn_df.to_dict(),outfile)

In [38]:
syn_df

          GC1  GC2  GC3  GC4  GC5
Exc_Cell
MC1         0    0    0    0    0
MC2         0    0    0    0    0
MC3         0    0    0    0    0
MC4       187    9  267   45   53
MC5       348   26  987  170  146
TC1         0    0    0    0    0
TC2         0    0    0    0    0
TC3         0    0    0    0    0
TC4         0    0    0    0    0
TC5         0    0    0    0    0

In [39]:

slices_dir = os.path.join('/home/ellismith/OlfactoryBulb/olfactorybulb/slices')

file_names = ['GCs__TCs']

for file_name in file_names:

    # import file into a dictionary
    with open(f'{slices_dir}/DorsalColumnSlice/{file_name}.json','r') as f:
        cells = json.load(f)

    # iterate over connections (entries) in file
    for entry in cells['entries']:
        # get the source and destination cell types (first three characters, i.e. MC5, MC4, ...) 
        source_cell = entry['source_section'][:3]
        dest_cell = entry['dest_section'][:3]

        # check that all synapses are reciprocal
        assert entry['is_reciprocal'] == True 
        
        # increment synapse counts - all GCs are sources and all MCs and TCs are dest's
        syn_df.loc[dest_cell][source_cell] = syn_df.loc[dest_cell][source_cell] + 1


    # write DataFrame to pickle (for reimporting as a DataFrame) and yaml (for viewing) files
    syn_df.to_pickle(f'{slices_dir}/{file_name}_synapse_counts.pkl', protocol=3)
    with open(f'{slices_dir}/{file_name}_synapse_counts.yaml', 'w') as outfile:
        yaml.dump(syn_df.to_dict(),outfile)

In [40]:
syn_df

          GC1  GC2  GC3  GC4  GC5
Exc_Cell
MC1         0    0    0    0    0
MC2         0    0    0    0    0
MC3         0    0    0    0    0
MC4       187    9  267   45   53
MC5       348   26  987  170  146
TC1         0    0    0    0    0
TC2         0    0    0    0    0
TC3        35    0    6   13    0
TC4       371    0  524  219   64
TC5       165    0  179  105   70